name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Ensure Gradle wrapper exists
        run: |
          cd $GITHUB_WORKSPACE/project  # 使用 GITHUB_WORKSPACE 环境变量作为根目录
          ./gradlew wrapper

      - name: Make Gradlew executable
        run: |
          cd $GITHUB_WORKSPACE/project  # 确保在项目目录中
          chmod +x ./gradlew

      - name: Build the app
        working-directory: $GITHUB_WORKSPACE/project  # 设置工作目录为项目目录
        run: ./gradlew assembleDebug --warning-mode all --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-build-apk
          path: $GITHUB_WORKSPACE/project/app/build/outputs/**/*.apk
