name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Ensure Gradle wrapper exists
        run: |
          cd ./project
          ./gradlew wrapper
        working-directory: ./project

      - name: Make Gradlew executable
        run: chmod +x ./project/gradlew

      - name: Build the app
        working-directory: ./project
        run: ./gradlew assembleDebug --warning-mode all --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-build-apk
          path: ./project/app/build/outputs/**/*.apk
