name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - id: get-project
        name: Get project name
        run: echo "::set-output name=PROJECT::$(cat project-to-build)"

      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project

      - name: Build the app
        working-directory: ./project
        run: |
          cd app  # 这里假设你的项目结构中包含一个名为 'app' 的子目录，如果不是，请根据实际情况修改路径
          if [ ! -f "gradlew" ]; then chmod +x gradle/wrapper/gradlew; fi
          ./gradlew assembleDebug --stacktrace --warning-mode all

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-build-apk
          path: ./**/*.apk
